blog/urls.py
# post/urls.py

from django.urls import path
from .views import post_list_view, post_detail_view, add_post_view

urlpatterns = [
    path('', post_list_view, name='post_list'),  # List view of posts
    path('<int:pk>/', post_detail_view, name='post_detail'),  # Detail view for a specific post
    path('add/', add_post_view, name='add_post'),  # Detail view for a specific post
    
]

quirk_chronicles/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static  # Import static to serve media files


urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('core.urls')),
    path("post/", include('blog.urls')),
    path("user/",include('user.urls'))
    
]

# Serve media files during development
if settings.DEBUG:  # Only in development, not in production
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path # type: ignore
from . import views

app_name = 'user'
urlpatterns = [
    
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.user_signup, name="signup")

]

user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

# Create your views here.
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, 'Login Successful!!')

            next_url = request.GET.get('next', 'post_list')
            return redirect(next_url)
        else:
            messages.error(request, 'Invalid username or password. Aaaaa')
        
    return render(request, 'user/login.html')


def user_logout(request):
    logout(request)
    messages.success(request,'You have been logged out.')
    return redirect('dashboard')

def user_signup(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        email = request.POST.get("email")
        confirm_password = request.POST.get("confirm_password")
        
        if password != confirm_password:
            messages.error(request, "Password do not match")
            return redirect('signup')
        
        if User.objects.filter(username=username).exists():
            messages.error(request, 'Username Already Exists.')
            return redirect('signup')
        
        if User.objects.filter(email=email).exists():
            messages.error(request, 'Email Already Used to create account.')
            return redirect('signup')
        
        if email=='' or username == '' or password == '':
            messages.error(request, 'Fields cannot be empty.')
            return redirect('signup')
        
        user = User.objects.create_user(username=username, password=password, email=email)
        user.save()
        login(request, user)
        messages.success(request, "Signup successful!!")
        return redirect('post_list')
    
    return render(request, 'user/signup.html')

user/templates/user/login.html
{%extends "core/base.html"%}

{%block title%}Login{%endblock%}

{%block content%}

    <h1>Login</h1>

    {%if messages%}
        {%for message in messages%}

            <p>{{message}}</p>
        {%endfor%}

    {% endif %}

    <form method="POST">
        {%csrf_token%}

        <label for="username">Username:</label>
        <input type="text" name="username" id="username" required>
        <br>
        <label for="password">Username:</label>
        <input type="password" name="password" id="password" required>
        <br>
        <button type="submit">Login</button>
    </form>

    <p>Don't have an account!!!! <a href={%url 'user:signup'%}>Then Login</a></p>

{%endblock%}

user/templates/user/signup.html
{%extends 'core/base.html'%}

{%block title%}Sign Up{%endblock%}

{%block content%}

    <h1>Signup</h1>

    {%if messages%}
        {%for message in messages%}
            <p>message</P>
        {%endfor%}
    {%endif%}


    <form method="POST" class="card">
        {% csrf_token %}
        <label for="username">Username: </label>
        <br>
        <input type="text" name="username" id="username" placeholder="Give the username!!" required>
        
        <br>
        
        <label for="password">Password: </label>
        <br>
        <input type="password" name="password" id="password" required>
        
        <br>
        
        <label for="confirm_password">Confirm_Password: </label>
        <br>
        <input type="password" name="confirm_password" id="confirm_password" required>
        
        <br>
        
        <label for="email">email: </label>
        <br>
        <input type="email" name="email" id="email" placeholder="Give the Email!!" required>
        
        <br>
        <br>
        <button type="submit">Signup</button>
    </form>

    <p>Already have an account!!!! <a href={%url 'user:login'%}>Then Login</a></p>
{%endblock%}